---
title: "Day 3 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(igraph)
library(ggplot2)
library(rgl)
library(ggraph)
library(reshape2)
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
input<-read_lines("Day3Sample.txt")

batterybank<-lapply(input,function(x){
  a<-as.numeric(unlist(str_split(x,"")))
})
```

Part 1

### find the max joltage

```{r}
batterymax<-function(bank){
  tensdigit<-max(bank[1:(length(bank)-1)])
  tensdigitplace<-which.max(bank[1:(length(bank)-1)])
  onesdigit<-max(bank[(tensdigitplace+1):length(bank)])
  return(tensdigit*10+onesdigit)}

```


```{r}
totaljoltage<-function(batterybank){
  tj<-sum(sapply(batterybank,batterymax))
  tj}
```

```{r}
totaljoltage(batterybank)
```

Part 2
Pretty much the same, except instead of leaving out the last digit, leave out the last 11 (and then work down)

```{r}
multidigitjolt<-function(bank,digits){
  tj<-0
  for(i in (digits-1):1){
    tj<-tj*10
    nextdigit<-max(head(bank,-i))
    tj<-tj+nextdigit
    nextdigitplace<-which.max(head(bank,-i))
    bank<-bank[-(1:nextdigitplace)]}
  tj<-(tj*10)+max(bank)
  
tj}
```

```{r}
totaljoltagemulti<-function(batterybank,d){
  tj<-sum(sapply(batterybank,function(x){multidigitjolt(x,d)}))
  tj}
```

```{r}
totaljoltagemulti(batterybank,12)
```

