rmarkdown::render('Day 1/Day1.Rmd',output_file="Day-1.html",output_dir="docs")
rmarkdown::render('Day 2/Day2.Rmd',output_file="Day-2.html",output_dir="docs")
rmarkdown::render('Day 3/Day3.Rmd',output_file="Day-3.html",output_dir="docs")
rmarkdown::render('Day 4/Day4.Rmd',output_file="Day-4.html",output_dir="docs")
rmarkdown::render('Day 5/Day5.Rmd',output_file="Day-5.html",output_dir="docs")
rmarkdown::render('Day 6/Day6.Rmd',output_file="Day-6.html",output_dir="docs")
rmarkdown::render('Day 7/Day7.Rmd',output_file="Day-7.html",output_dir="docs")
rmarkdown::render('Day 8/Day8.Rmd',output_file="Day-8.html",output_dir="docs")
rmarkdown::render('Day 9/Day9.Rmd',output_file="Day-9.html",output_dir="docs")
rmarkdown::render('Day 10/Day10.Rmd',output_file="Day-10.html",output_dir="docs")
rmarkdown::render('Day 11/Day11.Rmd',output_file="Day-11.html",output_dir="docs")
rmarkdown::render('Day 12/Day12.Rmd',output_file="Day-12.html",output_dir="docs")
rmarkdown::render('index.Rmd',output_file="index.html",output_dir="docs")