---
title: "Day 4 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(gganimate)
library(ggraph)
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
options(scipen = 999)
```

```{r}
input<-read_lines("Day4Sample.txt")
```


## Part 1

```{r}
### Setup
### replace "." with 0 & "@" with 1

room<-matrix(0,nrow=length(input)+2,ncol=nchar(input[1])+2)
for(i in 1:length(input)){
  r<-str_replace_all(str_replace_all(input[i],"@","1"),"\\.","0")
  room[(i+1),]<-c(0,as.numeric(unlist(str_split(r,""))),0)}

```

```{r}
forkliftable<-function(room){
  can_access<-0
  for(i in 2:(ncol(room)-1)){
    for(j in 2:(nrow(room)-1)){
      if(room[i,j]==1&&(sum(room[(i-1):(i+1),(j-1):(j+1)]))<=4){
        can_access<-can_access+1}}}
  can_access}
```

```{r}
forkliftable(room)
```
## Part 2

```{r}
paperless<-function(room){
  startingamount<-sum(room)
  doneyet<-FALSE
  counter<-0
  while(!doneyet){
    doneyet<-TRUE
    nextroom<-room
    for(i in 2:(ncol(room)-1)){
      for(j in 2:(nrow(room)-1)){
        if(room[i,j]==1&&(sum(room[(i-1):(i+1),(j-1):(j+1)]))<=4){
          nextroom[i,j]<-0
          doneyet<-FALSE}}}
    room<-nextroom}
  startingamount-sum(room)}
```


```{r}
paperless(room)
```